#!/bin/sh

. "$(dirname "$0")/.common.sh"

mkdir -p "${deb_cache_dir}"
cp /var/lib/dpkg/status "$dpkg_status_save"

apt-get install -y cdbs cmake libxml-security-c-dev xsdcxx doxygen zlib1g-dev

src=$(dl_cache_dir="$deb_cache_dir" dl_file "$esteid_repo/libdigidocpp.git")
(cd "$src"; dpkg-buildpackage -us -uc -b)
(cd "$deb_cache_dir"; dpkg-scanpackages . >Packages)

echo deb file://$deb_cache_dir ./ >/etc/apt/sources.list.d/build-esteid.list

apt_lists_file="$(find_apt_fullpath Dir::State::lists)/$(echo "$deb_cache_dir/./Packages" | tr / _)"
test ! -e "$apt_lists_file" || rm -f "$apt_lists_file"
ln -s $deb_cache_dir/Packages "$apt_lists_file"
