#!/bin/sh

. "$(dirname "$0")/.common.sh"

: ${pkgs:=qdigidoc qesteidutil chrome-token-signing}

apt-get install --force-yes -y libdigidocpp-dev libldap2-dev libpcsclite-dev qtbase5-dev qttools5-dev \
    qttools5-dev-tools

for pkg in $pkgs;do
  src=$(dl_cache_dir="$deb_cache_dir" dl_file "$esteid_repo/$pkg.git")
  (cd "$src"; dpkg-buildpackage -us -uc -b)
done

(cd "$deb_cache_dir"; dpkg-scanpackages . >Packages)

dpkg_status="$dpkg_status_save" "$lbu/scripts/apt-sfs.sh" "$DESTDIR" $pkgs
